# Generated by Django 3.2 on 2022-03-06 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название проекта')),
                ('repo_link', models.URLField(blank=True, verbose_name='ссылка на репозиторий')),
                ('developers', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='пользователи проекта')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024, verbose_name='текст заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='модифицирована')),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='todoapp.project', verbose_name='Заметка проекта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='от пользователя')),
            ],
        ),
    ]
